name: leeshare
description: A Flutter Windows file-sharing app using WiFi as a medium.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lan_sharing: ^0.1.1
  file_picker: ^6.1.1
  permission_handler: ^11.2.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.0
  logger: ^2.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
