dependencies:
  flutter:
    sdk: flutter
  lan_sharing: ^0.1.1
  file_picker: ^6.1.1
  permission_handler: ^11.2.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
